@echo off
echo %date% %time%
echo Compiling...
gcc src/* release/assets/images/icons/icon.o -o game -lncurses -lSDL2_mixer -Wall -Werror -Wpedantic -mconsole -fstack-protector -O3
echo Changing MZ Header...
powershell -noprofile -executionpolicy bypass -file ./scripts/executableTextAlteration.ps1
echo Sorting Files...
move .\game.exe .\release\game.exe
